-- endsong-action.lua
-- Fires ONCE, directly triggered by an SWS Marker Action (no background loop,
-- no ongoing CPU cost). Place a marker named "!_<this-script's-command-id>"
-- at the end of each song's timeline — see ENDSONG-MARKER.txt for the exact
-- string to use, generated by install.lua.
--
-- On trigger:
--   1. Stops playback
--   2. Switches to the next project tab
--   3. Moves the playhead to that project's "StartSong" marker (does not auto-play)

reaper.Main_OnCommand(1016, 0)    -- Transport: Stop
reaper.Main_OnCommand(40861, 0)   -- Next project tab

-- Find "StartSong" marker in the now-active (new) project
local i = 0
while true do
  local retval, isrgn, pos, _, name = reaper.EnumProjectMarkers(i)
  if retval == 0 then break end
  if not isrgn and name == "StartSong" then
    reaper.SetEditCurPos(pos, true, false)
    break
  end
  i = i + 1
end
